version: '3.4'

services:
  fencesserver:
    image: ghcr.io/ertustoresabligant/fences-server:latest
    init: true      # https://www.kaggle.com/code/residentmario/best-practices-for-propagating-signals-on-docker/notebook
    environment:
      NODE_ENV: production
      PORT: 3142
    ports:
      - 3142:3142
    restart: unless-stopped
    volumes:
      - fences_data:/usr/src/app/data

volumes:
  fences_data:
