#
# This workflow Build and Push Docker Image
#

name: CI - Fences Server

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker Image Tag"
        required: true
        default: "latest"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Push Docker Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHCR_PAT }}
          submodules: true
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          # platforms: linux/amd64,linux/arm64, linux/arm/v7
          push: true
          tags: |
            ghcr.io/ertustoresabligant/fences-server:${{ github.event.inputs.tag }} , ghcr.io/ertustoresabligant/fences-server:latest
